name: alok
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: 
  firebase_auth: 
  firebase_core: 
  introduction_screen: 
  get: 
  flutter_native_splash: 
  google_sign_in: 
  firebase_messaging: 
  comment_box: 
  path_provider: 
  get_storage: 
  hive: 
  cloud_firestore: 
  hive_flutter: 
  just_audio: 
  avatar_glow: 
  sliding_sheet: 
  animated_splash_screen: 
  splash_screen_view: 
  audio_video_progress_bar: 
  
  snapping_sheet:  
  store_redirect:  
  adaptive_action_sheet:  
  auto_size_text:  
  google_fonts:  
  just_audio_background:  
  rxdart: 
  just_audio_libwinmedia: 
  animations:  
  page_transition:  
  loader_overlay:  
  settings_ui:  
  # flutter_spinkit: ^5.1.0
  # badges: ^2.0.2
  cool_alert:  
  shared_preferences:  
  share_plus:  
  
flutter_native_splash:
  branding : "assets/1204.png"
  image: "assets/1024.png"
  android_gravity: center
  color: "#FFFFFF"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/1st.png
    - assets/1024.png
    - assets/2.png
    - assets/3rd.png
    - assets/bookmark.png
    - assets/comment.png
    - assets/dark_mode.png
    - assets/download.png
    - assets/good_comment.png
    - assets/goodsearch.png
    - assets/google.png
    - assets/listenbook.png
    - assets/love.png
    - assets/logo.png
    - assets/hello.png
    - assets/search.png
    - assets/soon.png
    - assets/student.png
    - assets/take_notes.png
    - assets/user.png
    - assets/network_issue.png
    - assets/no_data.png
    - assets/instagram.png
    - assets/telegram.png
    - assets/twitter1.png
    - assets/gmail_icon.png
    - assets/youtube.png
    - assets/oops.png    
    - assets/text-files/aboutus.txt
    - assets/text-files/privacy.txt
    - assets/text-files/terms.txt

