name: alok
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.17
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  introduction_screen: ^3.0.2
  get: ^4.6.1
  flutter_native_splash: ^2.2.0+1
  google_sign_in: ^5.2.1
  firebase_messaging: ^13.0.0
  comment_box: ^0.0.16
  path_provider: ^2.0.8
  get_storage: ^2.0.3
  hive: ^2.0.5
  cloud_firestore: ^3.1.6
  hive_flutter: ^1.1.0
  just_audio: ^0.9.18
  avatar_glow: ^2.0.2
  sliding_sheet: ^0.5.2
  animated_splash_screen: ^1.1.0
  splash_screen_view: ^3.0.0
  audio_video_progress_bar: ^0.10.0
  snapping_sheet: ^3.1.0
  store_redirect: ^2.0.0
  adaptive_action_sheet: ^2.0.1
  auto_size_text: ^3.0.0
  google_fonts: ^3.0.1
  just_audio_background: ^0.0.1-beta.3
  rxdart: ^0.27.3
  just_audio_libwinmedia: ^0.0.4
  animations: ^2.0.2
  page_transition: ^2.0.1-nullsafety.0
  loader_overlay: ^2.0.5
  settings_ui: ^2.0.2
  flutter_spinkit: ^5.1.0
  badges: ^2.0.2
  cool_alert: ^1.1.0
  shared_preferences: ^2.0.13
  share_plus: ^4.0.4
  
flutter_native_splash:
  branding : "assets/1204.png"
  image: "assets/1024.png"
  android_gravity: center
  color: "#FFFFFF"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/1st.png
    - assets/1024.png
    - assets/2.png
    - assets/3rd.png
    - assets/bookmark.png
    - assets/comment.png
    - assets/dark_mode.png
    - assets/download.png
    - assets/good_comment.png
    - assets/goodsearch.png
    - assets/google.png
    - assets/listenbook.png
    - assets/love.png
    - assets/logo.png
    - assets/hello.png
    - assets/search.png
    - assets/soon.png
    - assets/student.png
    - assets/take_notes.png
    - assets/user.png
    - assets/network_issue.png
    - assets/no_data.png
    - assets/instagram.png
    - assets/telegram.png
    - assets/twitter1.png
    - assets/gmail_icon.png
    - assets/youtube.png
    - assets/oops.png    
    - assets/text-files/aboutus.txt
    - assets/text-files/privacy.txt
    - assets/text-files/terms.txt

